spring:
  application:
    name: oss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.191.224:3306/oss_test
    username: root
    password: shen0602
server:
  port: 9000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
